local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["5"] = 1,["6"] = 1,["7"] = 1,["8"] = 1,["9"] = 1,["10"] = 1,["11"] = 1,["12"] = 1,["13"] = 1,["14"] = 1,["15"] = 1,["16"] = 1,["17"] = 1,["18"] = 1,["19"] = 1,["20"] = 1,["21"] = 1,["22"] = 1,["23"] = 1,["24"] = 1,["25"] = 1,["26"] = 1,["27"] = 1,["28"] = 1,["29"] = 1,["30"] = 1,["31"] = 1,["32"] = 1,["33"] = 1,["34"] = 33});
local ____exports = {}
local LightningEffects = LightningEffects or ({})
LightningEffects.CHAIN_LIGHTNING_PRIMARY = "CLPB"
LightningEffects.CHAIN_LIGHTNING_SECONDARY = "CLSB"
LightningEffects.DRAIN = "DRAB"
LightningEffects.DRAIN_LIFE = "DRAL"
LightningEffects.DRAIN_MANA = "DRAM"
LightningEffects.FINGER_OF_DEATH = "AFOD"
LightningEffects.FORKED_LIGHTNING = "FORK"
LightningEffects.HEALING_WAVE_PRIMARY = "HWPB"
LightningEffects.HEALING_WAVE_SECONDARY = "HWSB"
LightningEffects.LIGHTNING_ATTACK = "CHIM"
LightningEffects.MAGIC_LEASH = "LEAS"
LightningEffects.MANA_BURN = "MBUR"
LightningEffects.MANA_FLARE = "MFPB"
LightningEffects.SPIRIT_LINK = "SPLK"
LightningEffects.shan_dian_lian_zhu = "CLPB"
LightningEffects.shan_dian_lian_ci = "CLSB"
LightningEffects.ji_qu = "DRAB"
LightningEffects.sheng_ming_ji_qu = "DRAL"
LightningEffects.mo_fa_ji_qu = "DRAM"
LightningEffects.si_wang_zhi_zhi = "AFOD"
LightningEffects.cha_zhuang_shan_dian = "FORK"
LightningEffects.yi_liao_bo_zhu = "HWPB"
LightningEffects.yi_liao_bo_ci = "HWSB"
LightningEffects.shan_dian_gong_ji = "CHIM"
LightningEffects.ma_fa_liao_kao = "LEAS"
LightningEffects.fa_li_ran_shao = "MBUR"
LightningEffects.mo_li_zhi_yan = "MFPB"
LightningEffects.ling_hun_suo_lian = "SPLK"
____exports.default = LightningEffects
return ____exports
