local ____lualib = require("lualib_bundle")
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["6"] = 4,["7"] = 4,["8"] = 4,["9"] = 4,["10"] = 4,["11"] = 4,["12"] = 4,["13"] = 4,["14"] = 4,["15"] = 4,["16"] = 4,["17"] = 4,["18"] = 4,["19"] = 4,["20"] = 4,["21"] = 4,["22"] = 4,["23"] = 4,["24"] = 4,["25"] = 4,["26"] = 4,["27"] = 4,["28"] = 4,["29"] = 4,["30"] = 4,["31"] = 4,["32"] = 4,["33"] = 4,["34"] = 4,["35"] = 4,["36"] = 4,["37"] = 4,["38"] = 4,["39"] = 4,["40"] = 4,["41"] = 4,["42"] = 4,["43"] = 4,["44"] = 4,["45"] = 4,["46"] = 4,["47"] = 4,["48"] = 4,["49"] = 4,["50"] = 4,["51"] = 4,["52"] = 4,["53"] = 4,["54"] = 4,["55"] = 58});
local ____exports = {}
--- 共计23种武器类型 可以自行对应这些类型到自己的设计的属性上
local WeaponType = WeaponType or ({})
WeaponType.T0_WHOKNOWS = 0
WeaponType[WeaponType.T0_WHOKNOWS] = "T0_WHOKNOWS"
WeaponType.T1_METAL_LIGHT_CHOP = 1
WeaponType[WeaponType.T1_METAL_LIGHT_CHOP] = "T1_METAL_LIGHT_CHOP"
WeaponType.T2_METAL_MEDIUM_CHOP = 2
WeaponType[WeaponType.T2_METAL_MEDIUM_CHOP] = "T2_METAL_MEDIUM_CHOP"
WeaponType.T3_METAL_HEAVY_CHOP = 3
WeaponType[WeaponType.T3_METAL_HEAVY_CHOP] = "T3_METAL_HEAVY_CHOP"
WeaponType.T4_METAL_LIGHT_SLICE = 4
WeaponType[WeaponType.T4_METAL_LIGHT_SLICE] = "T4_METAL_LIGHT_SLICE"
WeaponType.T5_METAL_MEDIUM_SLICE = 5
WeaponType[WeaponType.T5_METAL_MEDIUM_SLICE] = "T5_METAL_MEDIUM_SLICE"
WeaponType.T6_METAL_HEAVY_SLICE = 6
WeaponType[WeaponType.T6_METAL_HEAVY_SLICE] = "T6_METAL_HEAVY_SLICE"
WeaponType.T7_METAL_MEDIUM_BASH = 7
WeaponType[WeaponType.T7_METAL_MEDIUM_BASH] = "T7_METAL_MEDIUM_BASH"
WeaponType.T8_METAL_HEAVY_BASH = 8
WeaponType[WeaponType.T8_METAL_HEAVY_BASH] = "T8_METAL_HEAVY_BASH"
WeaponType.T9_METAL_MEDIUM_STAB = 9
WeaponType[WeaponType.T9_METAL_MEDIUM_STAB] = "T9_METAL_MEDIUM_STAB"
WeaponType.T10_METAL_HEAVY_STAB = 10
WeaponType[WeaponType.T10_METAL_HEAVY_STAB] = "T10_METAL_HEAVY_STAB"
WeaponType.T11_WOOD_LIGHT_SLICE = 11
WeaponType[WeaponType.T11_WOOD_LIGHT_SLICE] = "T11_WOOD_LIGHT_SLICE"
WeaponType.T12_WOOD_MEDIUM_SLICE = 12
WeaponType[WeaponType.T12_WOOD_MEDIUM_SLICE] = "T12_WOOD_MEDIUM_SLICE"
WeaponType.T13_WOOD_HEAVY_SLICE = 13
WeaponType[WeaponType.T13_WOOD_HEAVY_SLICE] = "T13_WOOD_HEAVY_SLICE"
WeaponType.T14_WOOD_LIGHT_BASH = 14
WeaponType[WeaponType.T14_WOOD_LIGHT_BASH] = "T14_WOOD_LIGHT_BASH"
WeaponType.T15_WOOD_MEDIUM_BASH = 15
WeaponType[WeaponType.T15_WOOD_MEDIUM_BASH] = "T15_WOOD_MEDIUM_BASH"
WeaponType.T16_WOOD_HEAVY_BASH = 16
WeaponType[WeaponType.T16_WOOD_HEAVY_BASH] = "T16_WOOD_HEAVY_BASH"
WeaponType.T17_WOOD_LIGHT_STAB = 17
WeaponType[WeaponType.T17_WOOD_LIGHT_STAB] = "T17_WOOD_LIGHT_STAB"
WeaponType.T18_WOOD_MEDIUM_STAB = 18
WeaponType[WeaponType.T18_WOOD_MEDIUM_STAB] = "T18_WOOD_MEDIUM_STAB"
WeaponType.T19_CLAW_LIGHT_SLICE = 19
WeaponType[WeaponType.T19_CLAW_LIGHT_SLICE] = "T19_CLAW_LIGHT_SLICE"
WeaponType.T20_CLAW_MEDIUM_SLICE = 20
WeaponType[WeaponType.T20_CLAW_MEDIUM_SLICE] = "T20_CLAW_MEDIUM_SLICE"
WeaponType.T21_CLAW_HEAVY_SLICE = 21
WeaponType[WeaponType.T21_CLAW_HEAVY_SLICE] = "T21_CLAW_HEAVY_SLICE"
WeaponType.T22_AXE_MEDIUM_CHOP = 22
WeaponType[WeaponType.T22_AXE_MEDIUM_CHOP] = "T22_AXE_MEDIUM_CHOP"
WeaponType.T23_ROCK_HEAVY_BASH = 23
WeaponType[WeaponType.T23_ROCK_HEAVY_BASH] = "T23_ROCK_HEAVY_BASH"
____exports.default = WeaponType
return ____exports
